export const GET_LOCATION_DATA = "GET_LOCATION_DATA";
export const SHOW_FULL_MAP = "SHOW_FULL_MAP";
export const HANDLE_MAP_VIEW = "HANDLE_MAP_VIEW";
export const HANDLE_CARD_VIEW = "HANDLE_CARD_VIEW";
export const GET_LOCATION = "GET_LOCATION";
export const GET_ADDRESS = "GET_ADDRESS";
export const SHOW_HEADER= "SHOW_HEADER";
export const HIDE_HEADER= "HIDE_HEADER";
